---
nxos:
  hosts:
    nx-1:
      ansible_port: 22
      ansible_host: 192.168.1.248
      ansible_connection: ansible.netcommon.network_cli
      ansible_ssh_user: admin
      ansible_network_os: cisco.nxos.nxos
      ansible_ssh_pass: *
      ansible_ssh_common_args: -oHostKeyAlgorithms=+ssh-rsa


# [nxos] Fichier au format init bcp moins lisible 
# Faire des groupes qui contiendront les varibles pour un OS 
# nx-1 ansible_host=192.168.1.248 ansible_user=admin ansible_password=Cisco123cisco
