---
  - name: Deploiment de clef publique SSH sur NX OS
    hosts: nxos
    gather_facts: False

    vars_prompt:
    # Doc : https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_prompts.html
      - name: username
        prompt: Entrer un username pour l'accès SSH sur le switch. default
        private: false
        default: "sshuser"

    vars:
      ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" # Récupération de la clé publique SSH dans l'hote Ansible

    tasks:
      - setup:          
      # Permet d'accédé a certaine varible ex : ansible_date_time
          gather_subset:
          - 'min'
# ============================================================== #
# ========================= ONLY NX-OS ========================= #
# ============================================================== #
      - name: Sauvegarde de la configuration avant changement
        cisco.nxos.nxos_config:
        # J'ai essayer avec cisco.nxos.nxos_snapshot mais impossible version ?????
          backup: yes
          backup_options:
            filename: backup_{{ inventory_hostname }}_{{ ansible_date_time.time }}_{{ ansible_date_time.date }}.cfg
            # Nomentlature du backup : hostname_HH:MM:SS_YYYY-MM-DD.cfg
            dir_path: /home/raphael/backup/
        when: ansible_network_os == 'cisco.nxos.nxos'

      - name: Désactivation telnet
        cisco.nxos.nxos_feature:
          feature: telnet
          state: disabled
        when: ansible_network_os == 'cisco.nxos.nxos'

      - name: Configuration ssh / Ajout de la clef publique sur le switch depuis ~/.ssh/id_rsa.pub
        cisco.nxos.nxos_command:
          commands:
          - configure terminal
          - username {{ username }} role network-admin
          - username {{ username }} sshkey {{ ssh_key }}  # Utilisation de la variable ssh_key contenant la clé publique
          - command: "username {{ username }} keypair generate rsa 2048 force"
        when: ansible_network_os == 'cisco.nxos.nxos'    

# ============================================================== #
# ======================== /ONLY NX-OS/ ======================== #
# ============================================================== #


# ============================================================== #
# ========================== GENERALE ========================== #
# ============================================================== #
      - name: Enregistrement de la configuration
        cisco.nxos.nxos_command:
          commands:
          - copy running-config startup-config

# ========================= DEBUG ============================== #
# KING OF DEBUG : https://gryzli.info/2017/12/21/ansible-debug-print-variables/
      # - name: Display all variables/facts known for a host
      #   debug:
      #     var: hostvars[inventory_hostname]
      #   tags: debug_info
# ============================================================== #


# ============================================================== #
# ========================= /GENERALE/ ========================= #
# ============================================================== #